# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cvmat_dead <- function(image) {
    .Call('_opencv_cvmat_dead', PACKAGE = 'opencv', image)
}

cvmat_size <- function(image) {
    .Call('_opencv_cvmat_size', PACKAGE = 'opencv', image)
}

cvmat_new <- function() {
    .Call('_opencv_cvmat_new', PACKAGE = 'opencv')
}

cvmat_dupe <- function(image) {
    .Call('_opencv_cvmat_dupe', PACKAGE = 'opencv', image)
}

cvmat_read <- function(path) {
    .Call('_opencv_cvmat_read', PACKAGE = 'opencv', path)
}

cvmat_camera <- function() {
    .Call('_opencv_cvmat_camera', PACKAGE = 'opencv')
}

cvmat_write <- function(image, path) {
    .Call('_opencv_cvmat_write', PACKAGE = 'opencv', image, path)
}

cvmat_resize <- function(ptr, width = 0L, height = 0L) {
    .Call('_opencv_cvmat_resize', PACKAGE = 'opencv', ptr, width, height)
}

cvmat_bitmap <- function(ptr) {
    .Call('_opencv_cvmat_bitmap', PACKAGE = 'opencv', ptr)
}

cvmat_copyto <- function(from, to, mask) {
    .Call('_opencv_cvmat_copyto', PACKAGE = 'opencv', from, to, mask)
}

cvmat_info <- function(image) {
    .Call('_opencv_cvmat_info', PACKAGE = 'opencv', image)
}

cvmat_display <- function(ptr) {
    invisible(.Call('_opencv_cvmat_display', PACKAGE = 'opencv', ptr))
}

livestream <- function(filter) {
    invisible(.Call('_opencv_livestream', PACKAGE = 'opencv', filter))
}

cvmat_blur <- function(ptr, ksize) {
    .Call('_opencv_cvmat_blur', PACKAGE = 'opencv', ptr, ksize)
}

cvmat_sketch <- function(ptr, color) {
    .Call('_opencv_cvmat_sketch', PACKAGE = 'opencv', ptr, color)
}

cvmat_stylize <- function(ptr) {
    .Call('_opencv_cvmat_stylize', PACKAGE = 'opencv', ptr)
}

cvmat_face <- function(ptr, facedata, eyedata) {
    .Call('_opencv_cvmat_face', PACKAGE = 'opencv', ptr, facedata, eyedata)
}

cvmat_facemask <- function(ptr, facedata) {
    .Call('_opencv_cvmat_facemask', PACKAGE = 'opencv', ptr, facedata)
}

cvmat_mog2 <- function(ptr) {
    .Call('_opencv_cvmat_mog2', PACKAGE = 'opencv', ptr)
}

cvmat_knn <- function(ptr) {
    .Call('_opencv_cvmat_knn', PACKAGE = 'opencv', ptr)
}

cvmat_edges <- function(ptr) {
    .Call('_opencv_cvmat_edges', PACKAGE = 'opencv', ptr)
}

cvmat_hog <- function(ptr) {
    .Call('_opencv_cvmat_hog', PACKAGE = 'opencv', ptr)
}

cvmat_markers <- function(ptr) {
    .Call('_opencv_cvmat_markers', PACKAGE = 'opencv', ptr)
}

